version: "3.8"
services:
    busyboxhttpd:
        image: localhost:5000/some-content-busyboxhttpd:1.0
        volumes:
        - ./shared-html-directory:/var/www/html
        ports:
        - "8081:8081"
        networks:
        - web1
        deploy:
            resources:
              limits:
                cpus: '1'
                memory: 10M
    nginx:
        image: localhost:5000/some-content-nginx:1.0
        volumes:
        - ./shared-html-directory:/usr/share/nginx/html
        ports:
        - "8080:8080"
        networks:
        - web2
        deploy:
            resources:
              limits:
                cpus: '1'
                memory: 20M
networks:
    web1:
        driver: bridge
    web2:
        driver: bridge